### ISSUE TITLE
ask about installation

### ISSUE THREAD

**Issue by whatnowangga** [Leocoin-project/leocoinsight#1]
any documentaion for installation for this explorer ?
i have do with your step on README.
but i got something error

**Comment by whatnowangga** [comment]
```
LEOcoinsight-LEOcoincore@0.2.5 start /home/anggaand/Documents/explorer/leocoinsight
> INSIGHT_PUBLIC_PATH=public node node_modules/.bin/LEOcoinsight-api


module.js:340
    throw err;
          ^
Error: Cannot find module '/home/anggaand/Documents/explorer/leocoinsight/node_modules/.bin/LEOcoinsight-api'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0

```
